### PR TITLE
Building with responsive design

### PR DESCRIPTION
**Pull request by kiptubei**
This project entails the replication of [The next web](http://thenextweb.com/) which is is responsive as per the device the site is viewed on. The specifications include:

- Small (-sm-) devices (landscape phones, 400px and up) 
- Medium (-md-) devices (tablets, 768px and up) 
- Normal Screens (-l-) devices (laptops/notebooks 1024 and up) 
-  Extra large (-xl-) devices (large desktops, 1200px and up)

### CODE REVIEW

**Comment by kiptubei** [comment]
Accidentally added files to master instead of just the updated readme file. Fixed. and opened new pull request moved pull request to here [pull request](https://github.com/kiptubei/The-Next-Web/pull/4)

**Comment by adaorachi** [comment]
👋 @kiptubei  and @uimarshall,

Well done on the completion of the first draft of this project but sadly I cannot review the project. This Pull Request is closed and so, does not follow the proper Git Flow which is one of the validations a project must pass before it can be reviewed. 

I can see your comment above linking to another Pull Request but I cannot conform to it because it disrupts the use of GitFlow in a project. And so that other TSEs that might be reviewing your project in the future have the correct access to your Pull Request and see previous comments.

**I would advise you to submit another code review form with the correct Pull Request link.**

### **This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!**


Should you have any questions or need any help, please feel free to reach out to me on Slack with the username (@adaorachi). ☺️ 

**Happy Coding and Good-luck on it.**

**MaryAnn Chukwuka**

**Comment by kiptubei** [comment]
Hey MaryAnn,

Thanks for the comments. A new code review request has been submitted.

**Comment by adaorachi** [comment]
That's good, @kiptubei. 👍

**Pull request closed without merging**
